# ── Build stage ──────────────────────────────────────────────────────────────
FROM python:3.11-slim@sha256:d6e4d224f70f9e0172a06a3a2eba2f768eb146811a349278b38fff3a36463b47 AS builder

WORKDIR /build

# Install dependencies into an isolated directory so the final image
# only copies what's needed, keeping the image lean.
# requirements.lock is generated by pip-compile --generate-hashes and pins
# every transitive dependency to a specific hash, preventing silent substitution.
COPY requirements.txt requirements.lock ./
RUN pip install --no-cache-dir --require-hashes --prefix=/install -r requirements.lock

# Vendor frontend JS assets so the container has no runtime CDN dependency.
COPY scripts/download-vendor.sh /tmp/download-vendor.sh
RUN apt-get update -qq && apt-get install -y -q --no-install-recommends curl \
 && sh /tmp/download-vendor.sh /build/vendor \
 && apt-get purge -y curl && rm -rf /var/lib/apt/lists/*


# ── Runtime stage ─────────────────────────────────────────────────────────────
FROM python:3.11-slim@sha256:d6e4d224f70f9e0172a06a3a2eba2f768eb146811a349278b38fff3a36463b47

LABEL org.opencontainers.image.title="CAAMS Enterprise" \
      org.opencontainers.image.description="CAAMS Enterprise — Compliance Audit & Assessment Management System" \
      org.opencontainers.image.version="1.1.0"

# Non-root user for security
RUN groupadd -r caams && useradd -r -g caams -d /app -s /sbin/nologin caams

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /install /usr/local

# Copy application code
COPY app/        ./app/
COPY static/     ./static/
COPY migrations/ ./migrations/
COPY alembic.ini .
COPY seed.py     .
COPY entrypoint.sh .

# Copy vendored JS assets into the static directory
COPY --from=builder /build/vendor/ ./static/vendor/

# Runtime directories — writable by the caams user
RUN chmod +x entrypoint.sh \
 && mkdir -p uploads logs \
 && chown -R caams:caams /app

USER caams

# ── Environment defaults (override at runtime) ────────────────────────────────
# CAAMS_SECRET_KEY          — required; JWT signing key (min 32 chars)
# CAAMS_HOST                — bind address (default: 0.0.0.0)
# CAAMS_PORT                — port (default: 8000)
# CAAMS_ENABLE_DOCS         — set to "true" to expose /docs and /redoc
# CAAMS_ACCESS_TOKEN_MINUTES — JWT access token lifetime (default: 30)
# CAAMS_REFRESH_TOKEN_DAYS  — JWT refresh token lifetime (default: 7)
# CAAMS_MAX_UPLOAD_MB       — max upload size in MB for evidence & imports (default: 50)
# CAAMS_WORKERS             — number of uvicorn worker processes (default: 2)
#
# User invite flow (optional email delivery):
# CAAMS_INVITE_TOKEN_HOURS  — invite link lifetime in hours (default: 72)
# CAAMS_APP_BASE_URL        — frontend base URL for invite links (e.g. https://caams.co)
# CAAMS_SMTP_HOST           — SMTP server hostname (leave unset to disable email)
# CAAMS_SMTP_PORT           — SMTP port (default: 587)
# CAAMS_SMTP_FROM           — From address for outbound email
# CAAMS_SMTP_USER           — SMTP username (omit for anonymous relay)
# CAAMS_SMTP_PASSWORD       — SMTP password
# CAAMS_SMTP_USE_TLS        — "true" (default) uses STARTTLS; "false" for plain SMTP
ENV CAAMS_HOST=0.0.0.0 \
    CAAMS_PORT=8000 \
    CAAMS_WORKERS=2 \
    CAAMS_MAX_UPLOAD_MB=50 \
    CAAMS_INVITE_TOKEN_HOURS=72

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/ready', timeout=4)"

CMD ["./entrypoint.sh"]
